apiVersion: apps/v1
kind: Deployment
metadata:
  name: algoriddlebackendapi
  labels:
    app: algoriddlebackendapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algoriddlebackendapi
  template:
    metadata:
      labels:
        app: algoriddlebackendapi
    spec:
      containers:
      - name: api
        image: k3d-algoriddle:5000/algoriddlebackendapi:v0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        env:
          - name: SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT
          - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: algoriddle-secrets
                key: POSTGRES_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: algoriddle-secrets
                key: POSTGRES_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_JPA_HIBERNATE_DDL_AUTO
          - name: SPRING_JMS_SERVICEBUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: algoriddle-secrets
                key: SPRING_JMS_SERVICEBUS_CONNECTION_STRING
          - name: SPRING_JMS_SERVICEBUS_PRICING_TIER
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_JMS_SERVICEBUS_PRICING_TIER
          - name: SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: algoriddle-config
                key: SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
          - name: FIREBASE_CONFIG_JSON
            valueFrom:
              secretKeyRef:
                name: algoriddle-secrets
                key: FIREBASE_CONFIG_JSON
